name: 'mdex'
description: 'Generates indexes and vector embeddings from markdown files'
author: 'shmatt'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  path:
    description: 'The root path to the markdown files'
    required: false
    default: '/'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
