name: 'Markdown frontmatter index'
description:
  'Generates a json index of frontmatter extracted from markdown files'
author: 'shmatt'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'align-right'
  color: 'orange'

# Define your inputs here.
inputs:
  pattern:
    description: 'A glob pattern matching the files to parse for frontmatter'
    required: false
    default: '**/*.md'
  output:
    description: 'The path to write the json file to'
    required: false
    default: 'index.json'

# Define your outputs here.
outputs:
  indexPath:
    description: 'The path to the generated index file'

runs:
  using: node20
  main: dist/index.js
